### ISSUE TITLE
ChromecastSampleApp crashes on launch if expected version of Google Play Services is not installed

### ISSUE THREAD

**Issue by obec** [ooyala/android-sample-apps#30]
```
09-01 10:49:05.585  29983-29983/com.ooyala.sample.ChromecastSampleApp W/GooglePlayServicesUtil﹕ Google Play services out of date.  Requires 7895000 but found 7574038
09-01 10:49:05.585  29983-29983/com.ooyala.sample.ChromecastSampleApp E/CastManager﹕ Couldn't find the appropriate version of Google Play Services (code 2)
09-01 10:49:05.585  29983-29983/com.ooyala.sample.ChromecastSampleApp D/AndroidRuntime﹕ Shutting down VM
09-01 10:49:05.585  29983-29983/com.ooyala.sample.ChromecastSampleApp W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x417ddda0)
09-01 10:49:05.585  29983-29983/com.ooyala.sample.ChromecastSampleApp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ooyala.sample.ChromecastSampleApp, PID: 29983
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ooyala.sample.ChromecastSampleApp/com.ooyala.sample.ChromecastSampleApp.ChromecastListActivity}: java.lang.RuntimeException: Couldn't find the appropriate version of Google Play Services (code 2)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453)
            at android.app.ActivityThread.access$900(ActivityThread.java:173)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5579)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Couldn't find the appropriate version of Google Play Services (code 2)
            at com.ooyala.android.castsdk.CastManager.requireGooglePlayServices(CastManager.java:110)
            at com.ooyala.android.castsdk.CastManager.initialize(CastManager.java:98)
            at com.ooyala.sample.ChromecastSampleApp.ChromecastListActivity.onCreate(ChromecastListActivity.java:40)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453)
            at android.app.ActivityThread.access$900(ActivityThread.java:173)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5579)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

Expected: Update dialog provided through Google Play Services: https://developers.google.com/android/guides/setup#ensure_devices_have_the_google_play_services_apk

**Comment by jonslenkooyala** [comment]
Thank you for the report. We will work on this.

**Comment by jonslenkooyala** [comment]
This has been fixed in the dev branch, and will get into the next stable release.
