### ISSUE TITLE
AndroidX Migration of Ooyala SDK has made it impossible to upgrade to v4.41.0 when using the support libs

### ISSUE THREAD

**Issue by wezley98** [ooyala/android-sample-apps#409]
We are currently using v4.40.0, which works fine. After trying the upgrade to v4.41.0 we get the following crash at runtime. We don't currently use AndroidX in our projects, and can't move just yet as it is a large piece of work.

```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatTextView;
        at com.ooyala.android.skin.OoyalaReactPackage.createViewManagers(OoyalaReactPackage.java:62)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.AppCompatTextView" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.bskyb.vanguard-eBuPXpcM6TF1638_al0H9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.bskyb.vanguard-eBuPXpcM6TF1638_al0H9w==/lib/x86, /data/app/com.bskyb.vanguard-eBuPXpcM6TF1638_al0H9w==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.ooyala.android.skin.OoyalaReactPackage.createViewManagers(OoyalaReactPackage.java:62) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by hk-2016** [comment]
I have the same issue and I cannot find the source of the v4.40.0 so I cannot even downgrade.

Would you please send me a link for v4.40.0 to use it for now until we find a solution to this issue ?

**Comment by wezley98** [comment]
@SergeyBicarte @DmitriiMaslov @isheftel-ooyala any info on this issue? This is a blocker for us to upgrade to v4.41.0

**Comment by DmitriiMaslov** [comment]
@ahmedhassan1995 you can downgrade using this link https://s3.amazonaws.com/static.ooyala.com/sdk/android/release/versions/OoyalaSDKArchive-Android-4.40.0_RC10.zip
